//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.06 at 12:54:17 AM BDT 
//


package com.iict.buet.customer_portal.dbbl_gateway;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.iict.buet.customer_portal.dbbl_gateway package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Getransid_QNAME = new QName("http://ecom.dbbl/", "getransid");
    private final static QName _GetransidResponse_QNAME = new QName("http://ecom.dbbl/", "getransidResponse");
    private final static QName _Getresult_QNAME = new QName("http://ecom.dbbl/", "getresult");
    private final static QName _GetresultResponse_QNAME = new QName("http://ecom.dbbl/", "getresultResponse");
    private final static QName _Getresultfield_QNAME = new QName("http://ecom.dbbl/", "getresultfield");
    private final static QName _GetresultfieldResponse_QNAME = new QName("http://ecom.dbbl/", "getresultfieldResponse");
    private final static QName _Getsubmertransid_QNAME = new QName("http://ecom.dbbl/", "getsubmertransid");
    private final static QName _GetsubmertransidResponse_QNAME = new QName("http://ecom.dbbl/", "getsubmertransidResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.iict.buet.customer_portal.dbbl_gateway
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Getransid }
     * 
     */
    public Getransid createGetransid() {
        return new Getransid();
    }

    /**
     * Create an instance of {@link GetransidResponse }
     * 
     */
    public GetransidResponse createGetransidResponse() {
        return new GetransidResponse();
    }

    /**
     * Create an instance of {@link Getresult }
     * 
     */
    public Getresult createGetresult() {
        return new Getresult();
    }

    /**
     * Create an instance of {@link GetresultResponse }
     * 
     */
    public GetresultResponse createGetresultResponse() {
        return new GetresultResponse();
    }

    /**
     * Create an instance of {@link Getresultfield }
     * 
     */
    public Getresultfield createGetresultfield() {
        return new Getresultfield();
    }

    /**
     * Create an instance of {@link GetresultfieldResponse }
     * 
     */
    public GetresultfieldResponse createGetresultfieldResponse() {
        return new GetresultfieldResponse();
    }

    /**
     * Create an instance of {@link Getsubmertransid }
     * 
     */
    public Getsubmertransid createGetsubmertransid() {
        return new Getsubmertransid();
    }

    /**
     * Create an instance of {@link GetsubmertransidResponse }
     * 
     */
    public GetsubmertransidResponse createGetsubmertransidResponse() {
        return new GetsubmertransidResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Getransid }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Getransid }{@code >}
     */
    @XmlElementDecl(namespace = "http://ecom.dbbl/", name = "getransid")
    public JAXBElement<Getransid> createGetransid(Getransid value) {
        return new JAXBElement<Getransid>(_Getransid_QNAME, Getransid.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetransidResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetransidResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://ecom.dbbl/", name = "getransidResponse")
    public JAXBElement<GetransidResponse> createGetransidResponse(GetransidResponse value) {
        return new JAXBElement<GetransidResponse>(_GetransidResponse_QNAME, GetransidResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Getresult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Getresult }{@code >}
     */
    @XmlElementDecl(namespace = "http://ecom.dbbl/", name = "getresult")
    public JAXBElement<Getresult> createGetresult(Getresult value) {
        return new JAXBElement<Getresult>(_Getresult_QNAME, Getresult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetresultResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetresultResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://ecom.dbbl/", name = "getresultResponse")
    public JAXBElement<GetresultResponse> createGetresultResponse(GetresultResponse value) {
        return new JAXBElement<GetresultResponse>(_GetresultResponse_QNAME, GetresultResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Getresultfield }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Getresultfield }{@code >}
     */
    @XmlElementDecl(namespace = "http://ecom.dbbl/", name = "getresultfield")
    public JAXBElement<Getresultfield> createGetresultfield(Getresultfield value) {
        return new JAXBElement<Getresultfield>(_Getresultfield_QNAME, Getresultfield.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetresultfieldResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetresultfieldResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://ecom.dbbl/", name = "getresultfieldResponse")
    public JAXBElement<GetresultfieldResponse> createGetresultfieldResponse(GetresultfieldResponse value) {
        return new JAXBElement<GetresultfieldResponse>(_GetresultfieldResponse_QNAME, GetresultfieldResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Getsubmertransid }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Getsubmertransid }{@code >}
     */
    @XmlElementDecl(namespace = "http://ecom.dbbl/", name = "getsubmertransid")
    public JAXBElement<Getsubmertransid> createGetsubmertransid(Getsubmertransid value) {
        return new JAXBElement<Getsubmertransid>(_Getsubmertransid_QNAME, Getsubmertransid.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetsubmertransidResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetsubmertransidResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://ecom.dbbl/", name = "getsubmertransidResponse")
    public JAXBElement<GetsubmertransidResponse> createGetsubmertransidResponse(GetsubmertransidResponse value) {
        return new JAXBElement<GetsubmertransidResponse>(_GetsubmertransidResponse_QNAME, GetsubmertransidResponse.class, null, value);
    }

}
