//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.06 at 12:54:17 AM BDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ecom.dbbl/")
package com.iict.buet.customer_portal.dbbl_gateway;
